name: pilll
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 202312.15.060940+1671

environment:
  sdk: ">=3.0.0 <4.0.0"

platforms:
  android:
  ios:

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.9
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  firebase_core: ^2.21.0
  firebase_analytics: ^10.6.3
  firebase_auth: ^4.12.1
  firebase_messaging: ^14.7.3
  cloud_firestore: ^4.12.2
  url_launcher: ^6.2.1
  package_info: ^2.0.0
  equatable: ^2.0.0
  json_annotation: ^4.0.0
  mockito: ^5.3.2
  freezed_annotation: ^2.2.0
  riverpod: ^2.4.4
  hooks_riverpod: ^2.4.4
  riverpod_annotation: 2.3.0
  flutter_hooks: ^0.20.3
  firebase_crashlytics: ^3.0.12
  dotted_border: ^2.1.0
  in_app_review: ^2.0.8
  uuid: ^3.0.7
  async_value_group: ^1.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  flutter_app_badger: ^1.2.0
  purchases_flutter: ^5.7.0
  flutter_native_timezone: ^2.0.0
  flutter_local_notifications: ^15.1.2
  webview_flutter: ^4.4.2
  collection: 1.17.2
  crypto:
  timezone:
  firebase_remote_config: ^4.3.3
  google_mobile_ads: ^3.0.0

dev_dependencies:
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.3

  flutter_test:
    sdk: flutter
  build_runner: 2.4.6
  json_serializable:
  freezed: ^2.4.5
  custom_lint: 0.5.6
  riverpod_lint: 2.1.1
  riverpod_generator: 2.3.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true
  assets:
    - images/

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
