name: pilll
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 202601.07.190605

environment:
  sdk: ">=3.0.0 <4.0.0"

platforms:
  android:
  ios:

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.2.3
  shared_preferences: ^2.5.4
  intl: ^0.20.2
  firebase_core: ^4.3.0
  firebase_analytics:
  firebase_auth:
  firebase_messaging:
  firebase_remote_config:
  firebase_crashlytics:
  cloud_functions:
  cloud_firestore:
  url_launcher: ^6.3.2
  package_info_plus: ^8.0.2
  json_annotation: ^4.9.0
  mockito: ^5.4.4
  freezed_annotation: ^2.4.4
  riverpod: ^2.4.4
  hooks_riverpod: ^2.4.10
  riverpod_annotation: 2.3.5
  flutter_hooks: ^0.20.5
  dotted_border: ^2.1.0
  in_app_review: ^2.0.11
  uuid: ^4.5.2
  async_value_group: ^1.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_app_badger: ^1.2.0
  purchases_flutter: ^8.3.1
  flutter_local_notifications: ^19.5.0
  webview_flutter: ^4.13.0
  collection: ^1.18.0
  crypto: 3.0.7
  timezone: 0.10.1
  google_mobile_ads: ^5.0.0
    # home_widget: ^0.5.0
  home_widget:
    git:
      url: https://github.com/bannzai/home_widget.git
      ref: main
  path_provider: ^2.1.4
  flutter_timezone: ^4.1.0

dev_dependencies:
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

  flutter_test:
    sdk: flutter
  build_runner: 2.4.11
  json_serializable: 6.8.0
  freezed: ^2.5.2
  custom_lint: ^0.6.4
  riverpod_lint: 2.3.10
  riverpod_generator: 2.4.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true
  assets:
    - images/

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
